services:
  - type: web
    name: tetris-tournament-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: tetris-data
      mountPath: /app/data
      sizeGB: 1